Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-24.04"

 config.vm.network "forwarded_port",
  guest: 80,
  host: 8080,
  host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "cloud-lab-ubuntu"
    vb.memory = 2048
    vb.cpus = 2
  end
end